Repository un-ts/prettier, pull requests merged in 2022-07, with the labels that each got.

#195 docs: add Sponsors and Backers sections
  .changeset/config.json
  .changeset/short-icons-punch.md
  .eslintrc
  .eslintrc.cjs
  .github/FUNDING.yml
  .github/workflows/ci.yml
  .prettierrc
  .prettierrc.cjs
  README.md
  package.json
  packages/pkg/CHANGELOG.md
  packages/pkg/README.md
  packages/pkg/package.json
  packages/pkg/test/__snapshots__/test.spec.ts.snap
  packages/pkg/test/fixtures/fixture1.json
  packages/pkg/test/fixtures/fixture2.json
  packages/sh/CHANGELOG.md
  packages/sh/README.md
  packages/sh/package.json
  packages/sql/CHANGELOG.md
  packages/sql/README.md
  packages/sql/package.json
  scripts/format.ts
  vercel.json
  yarn.lock
Labels: documentation

#197 feat!: add donate field support
  .changeset/strange-terms-occur.md
  .github/FUNDING.yml
  packages/pkg/package.json
  packages/pkg/src/rules/sort.ts
  packages/sh/package.json
  packages/sql/package.json
Labels: internal

#199 feat(pkg)!: support more fields from yarn and vscode
  .changeset/stale-crabs-design.md
  .github/FUNDING.yml
  .github/workflows/pkg-size.yml
  .github/workflows/release.yml
  .github/workflows/vercel.yml
  packages/pkg/src/rules/sort.ts
Labels: enhancement, internal

#201 feat(sql)!: upgrade sql-formatter v8, remove deprecated options
  .changeset/hungry-melons-nail.md
  package.json
  packages/sql/package.json
  packages/sql/src/index.ts
  yarn.lock
Labels: breaking, dependencies

#205 docs(sql): align parser options
  .changeset/happy-lobsters-shop.md
  packages/sql/README.md
Labels: documentation

#207 feat(sql)!: respect `endOfLine` option from `prettier` core
  .changeset/sharp-actors-share.md
  packages/sql/src/index.ts
  packages/sql/test/__snapshots__/fixtures.spec.ts.snap
  packages/sql/test/__snapshots__/sql.spec.ts.snap
Labels: enhancement, feature, breaking, accepted

#209 feat(sh): new `experimentalWasm` option to use `sh-syntax`
  .changeset/afraid-crabs-grin.md
  .changeset/loud-vans-teach.md
  .changeset/tasty-carpets-divide.md
  .codesandbox/ci.json
  .eslintrc
  .gitattributes
  .github/workflows/ci.yml
  .github/workflows/pkg-size.yml
  .github/workflows/release.yml
  .npmrc
  .prettierignore
  auto-imports.d.ts
  package.json
  packages/pkg/src/index.ts
  packages/pkg/src/rules/files.ts
  packages/pkg/src/rules/object.ts
  packages/pkg/src/rules/sort.ts
  packages/pkg/src/types.ts
  packages/pkg/src/utils.ts
  packages/pkg/test/__snapshots__/engines.spec.ts.snap
  packages/pkg/test/__snapshots__/files.spec.ts.snap
  packages/pkg/test/__snapshots__/test.spec.ts.snap
  packages/pkg/test/engines.spec.ts
  packages/pkg/test/files.spec.ts
  packages/pkg/test/test.spec.ts
  packages/sh/README.md
  packages/sh/package.json
  packages/sh/src/index.ts
  packages/sh/src/worker.ts
  packages/sh/test/__snapshots__/fixture.spec.ts.snap
  packages/sh/test/__snapshots__/fixtures.spec.ts.snap
  packages/sh/test/__snapshots__/shellscript.spec.ts.snap
  packages/sh/test/fixture.spec.ts
  packages/sh/test/fixtures.spec.ts
  packages/sh/test/fixtures/146-wasm-no.ini
  packages/sh/test/fixtures/182-wasm-no
  packages/sh/test/shellscript.spec.ts
  packages/sql/package.json
  packages/sql/src/index.ts
  packages/sql/test/__snapshots__/fixtures.spec.ts.snap
  packages/sql/test/__snapshots__/sql.spec.ts.snap
  packages/sql/test/fixtures.spec.ts
  packages/sql/test/sql.spec.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  vitest.config.ts
  yarn.lock
Labels: enhancement, feature
